### ISSUE TITLE
Fix issues

### ISSUE THREAD

**Issue by coryhouse** [lulz010/ps-react-lulz010#1]
There are 3 issues:
1. https://www.dropbox.com/s/mu4y9wer4t5z9jk/Screenshot%202019-06-27%2012.46.53.png?dl=0
2. https://www.dropbox.com/s/05nx6ovn075urv0/Screenshot%202019-06-27%2012.47.03.png?dl=0
3. You need to create `src/examples/HelloWorld.js`

After that it should work. If not, reply here on this issue. I'm subscribed. Happy coding!

**Comment by lulz010** [comment]
It compiled! Thank you for finding these.

**Comment by coryhouse** [comment]
Great to hear! 👍  :)
